name: camsolution_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  easy_debounce: ^2.0.2+1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.1
  intl: ^0.17.0
  json_path: ^0.3.1
  page_transition: ^2.0.4
  timeago: ^3.1.0
  url_launcher: ^6.0.17

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:

  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
  fonts:
    - family: NatoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKhmer-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKhmer-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKhmer-Regular.ttf
        - asset: assets/fonts/NotoSansKhmer-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKhmer-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKhmer-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKhmer-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKhmer-Black.ttf
          weight: 900

